name: "chaos mesh k3d  ubuntu CI workflow"


on:
  push:
    branches: [ dev ]

jobs:

# https://gremlin.org/reference/usage/install/
  gremlin-ubuntu-latest-job:
    name: "chaos mesh k3d on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "Install chaos mesh k3d"
      run: |
        # Install Python
        sudo apt-get install python3
        sudo pip3 install virtualenv
        # Create a virtual environment
        virtualenv -p $(which python3) ~venvpy3
        source ~venvpy3/bin/activate
        pip install -r requirements.txt
        sudo make deploy-microk8s provision-helm
        
        

